-- CreateTable
CREATE TABLE "TradeOpportunity" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'imported',
    "source" TEXT NOT NULL DEFAULT 'oddsjam_paste',
    "rawEntryText" TEXT,
    "importedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "verifiedAt" DATETIME,
    "lockedAt" DATETIME,
    "skippedAt" DATETIME,
    "failedAt" DATETIME,
    "failureReason" TEXT,
    "notes" TEXT,
    "lockedTradeId" TEXT,
    "tradeType" TEXT NOT NULL DEFAULT 'cash_arbitrage',
    "event" TEXT NOT NULL,
    "startTime" DATETIME,
    "sport" TEXT NOT NULL DEFAULT 'unknown',
    "league" TEXT,
    "market" TEXT NOT NULL DEFAULT 'moneyline',
    "playerOrTeam" TEXT,
    "period" TEXT NOT NULL DEFAULT 'full_game',
    "bookAId" TEXT,
    "sideA" TEXT,
    "oddsA" INTEGER,
    "lineA" REAL,
    "stakeA" REAL,
    "liquidityA" REAL,
    "verifiedOddsA" INTEGER,
    "verifiedLineA" REAL,
    "verifiedLiquidityA" REAL,
    "bookANotes" TEXT,
    "bookAVerified" BOOLEAN NOT NULL DEFAULT false,
    "bookBId" TEXT,
    "sideB" TEXT,
    "oddsB" INTEGER,
    "lineB" REAL,
    "stakeB" REAL,
    "liquidityB" REAL,
    "verifiedOddsB" INTEGER,
    "verifiedLineB" REAL,
    "verifiedLiquidityB" REAL,
    "bookBNotes" TEXT,
    "bookBVerified" BOOLEAN NOT NULL DEFAULT false,
    "sameEventConfirmed" BOOLEAN NOT NULL DEFAULT false,
    "sameMarketConfirmed" BOOLEAN NOT NULL DEFAULT false,
    "samePlayerOrTeamConfirmed" BOOLEAN NOT NULL DEFAULT false,
    "samePeriodConfirmed" BOOLEAN NOT NULL DEFAULT false,
    "sameLineConfirmed" BOOLEAN NOT NULL DEFAULT false,
    "oppositeSidesConfirmed" BOOLEAN NOT NULL DEFAULT false,
    "oddsAcceptedConfirmed" BOOLEAN NOT NULL DEFAULT false,
    "stakeAcceptedConfirmed" BOOLEAN NOT NULL DEFAULT false,
    "liquidityEnoughConfirmed" BOOLEAN NOT NULL DEFAULT false,
    "recalculatedConfirmed" BOOLEAN NOT NULL DEFAULT false,
    "userFinalConfirm" BOOLEAN NOT NULL DEFAULT false,
    "totalExposure" REAL,
    "profitIfAWins" REAL,
    "profitIfBWins" REAL,
    "expectedProfitMin" REAL,
    "expectedProfitMax" REAL,
    "middleDistance" REAL,
    "middleNumber" REAL,
    "middleRange" TEXT,
    "outsideLoss" REAL,
    "middleProfit" REAL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "TradeOpportunity_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "TradeOpportunity_lockedTradeId_fkey" FOREIGN KEY ("lockedTradeId") REFERENCES "PaperTrade" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "TradeOpportunity_bookAId_fkey" FOREIGN KEY ("bookAId") REFERENCES "Book" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "TradeOpportunity_bookBId_fkey" FOREIGN KEY ("bookBId") REFERENCES "Book" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "TradeOpportunity_lockedTradeId_key" ON "TradeOpportunity"("lockedTradeId");

-- CreateIndex
CREATE INDEX "TradeOpportunity_userId_status_idx" ON "TradeOpportunity"("userId", "status");

-- CreateIndex
CREATE INDEX "TradeOpportunity_userId_importedAt_idx" ON "TradeOpportunity"("userId", "importedAt");
